name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version
        with:
          fetch-depth: 0  # Needed for proper SonarQube analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Updated to latest version
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle (if missing)
        run: |
          if [ ! -f gradlew ]; then
            echo "Gradle wrapper not found, installing Gradle..."
            sudo apt update && sudo apt install -y gradle
          fi

      - name: Ensure Gradle wrapper exists
        run: |
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Gradle wrapper is missing. Regenerating..."
            gradle wrapper  # Use system Gradle, NOT ./gradlew
          fi

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew  # Fixes "Permission denied" issue

      - name: Cache SonarQube packages
        uses: actions/cache@v3  # Updated to latest version
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}
          restore-keys: sonar-${{ runner.os }}

      - name: Cache Gradle packages
        uses: actions/cache@v3  # Updated to latest version
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Build and analyze with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonar --warning-mode all
